### ISSUE TITLE
[Feature Request] 是否能支持子应用为 vite形式

### ISSUE THREAD

**Issue by baby24007** [jd-opensource/jmodule#5]
是否能提供vite插件，支持子应用在开发环境能够集成联调和构建入口文件产物。

**Comment by feirpri** [comment]
[已处理](https://github.com/jd-opensource/jmodule/pull/7) 
通过 @jmodule/cli-bridge 方式进行开发环境调试.
通过 ResourceType: html 进行运行时集成
@baby24007
